experiment: "synth_betavae"

data:
  ntrain: 20000
  nvalidate: 10000
  ntest: 10000
  name: 'SynthDataset'
  d: 4
  gamma: 1
  alpha: 1

batch_size: 128

net:
  name: 'FCVAE'
  zdim: 4
  depth: 2
  depth_dec: 2
  width_dec: 64
  width: 64
  input_dim: 4
  learning_rate: 0.001
  activation: 'RELU'
  sdim: 2


loss:
  name: 'VAELoss'
  beta: 0.0

device: 'cpu'
n_epochs: 100
method: 'vae'
gamma: 0
beta: 0
nclass_outcome: 1
nclass_sensitive: 2