experiment: "synth_fbc"

data:
  ntrain: 20000
  nvalidate: 10000
  ntest: 10000
  name: 'SynthDataset'
  d: 4
  gamma: 1
  alpha: 2

batch_size: 128

net:
  name: 'FC'
  zdim: 4
  zk: 2
  k: 8
  depth: 2
  depth_dec: 2
  width_dec: 64
  width: 64
  input_dim: 4
  learning_rate: 0.001
  sigma: 1
  sdim: 10

pmodel:
  name: 'RegLayer'
  learning_rate: 0.0001
  out_features: 64
  k: 16
  in_features: 20
  out_dim: 1


loss:
  name: 'MILoss'

ploss:
  name: 'CECondLoss'

device: 'cpu'
n_epochs: 100
method: 'compression'
gamma: 0
beta: 0
nclass_outcome: 1
nclass_sensitive: 2