autoencoder: 'configs/synthetic/synth_fbc.yml'

probes_list:
  - 'configs/probes/multi_width_128_depth_2.yml'

task_list:
   - 'configs/probes/fc_width_128_depth_2.yml'

experiment_type: 'predict_outcome_sensitive'

seed: 0

name: 'synth_fbc_alpha2_exp5'

logging_dir: '/scratch/xgitiaux/Comp'

