experiment: "synth_fbc"

data:
  ntrain: 20000
  nvalidate: 10000
  ntest: 10000
  name: 'SynthDataset'
  d: 4
  gamma: 0
  alpha: 1

batch_size: 128

net:
  name: 'FCVAE'
  zdim: 4
  depth: 2
  depth_dec: 2
  width_dec: 64
  width: 64
  input_dim: 4
  learning_rate: 0.0001
  sdim: 2

pmodel:
  name: 'MLP'
  width: 64
  depth: 2
  learning_rate: 0.0001
  zdim: 4
  nclass: 2


loss:
  name: 'L2Loss'

ploss:
  name: 'MCELoss'

device: 'cpu'
n_epochs: 100
method: 'adversarial'
gamma: 0
beta: 0
nclass_outcome: 1
nclass_sensitive: 2