experiment: "adult_fbc"

data:
  train: '../data/to-ml-adult/adult.data'
  validate: '../data/to-ml-adult/adult.validate'
  test: '../data/to-ml-adult/adult.test_true'
  name: 'AdultDataSet'
  seed: 0

batch_size: 128

net:
  name: 'FC'
  zdim: 10
  zk: 10
  k: 4
  depth: 2
  depth_dec: 2
  width_dec: 64
  width: 64
  input_dim: 9
  learning_rate: 0.001
  sigma: 1
  sdim: 10

pmodel:
  name: 'RegLayer'
  learning_rate: 0.0001
  out_features: 64
  k: 40
  in_features: 40
  out_dim: 1

loss:
  name: 'MILoss'

ploss:
  name: 'CECondLoss'

device: 'cpu'
n_epochs: 200
method: 'compression'
gamma: 0
beta: 0
nclass_outcome: 1
nclass_sensitive: 10
