experiment: "adult_adv"

data:
  train: '../data/to-ml-adult/adult.data'
  validate: '../data/to-ml-adult/adult.validate'
  test: '../data/to-ml-adult/adult.test_true'
  name: 'AdultDataSet'
  seed: 0
  range_data: 10000

batch_size: 128

net:
  name: 'FCVAE'
  zdim: 10
  depth: 2
  depth_dec: 2
  width_dec: 64
  width: 64
  input_dim: 9
  learning_rate: 0.001
  sdim: 10

pmodel:
  name: 'MLP'
  width: 64
  depth: 2
  learning_rate: 0.0001
  zdim: 10
  nclass: 10

loss:
  name: 'L2Loss'

ploss:
  name: 'MCELoss'

device: 'cpu'
n_epochs: 200
method: 'adversarial'
gamma: 0
beta: 0
nclass_outcome: 1
nclass_sensitive: 10
