autoencoder: 'configs/dsprites/dsprites_mmd.yml'

probes_list:
  - 'configs/probes/multi_width_32_depth_4.yml'

task_list:
  - 'configs/probes/multi_width_32_depth_4.yml'

experiment_type: 'predict_outcome_sensitive'

seed: 0

name: 'dsprites_mmd_auditor'

logging_dir: './summaries'

checkpoints: './checkpoints'
