experiment: "heritage-fbc"

data:
  train: 'data/to-ml-heritage/heritage-train.csv'
  validate: 'data/to-ml-heritage/heritage-validate.csv'
  test: 'data/to-ml-heritage/heritage-test.csv'
  name: 'HeritageDataset'

batch_size: 128

net:
  name: 'FC'
  zdim: 24
  depth: 2
  depth_dec: 2
  width_dec: 128
  width: 128
  input_dim: 65
  learning_rate: 0.0005
  sigma: 10
  k: 8
  zk: 18
  sdim: 18

pmodel:
  name: 'PixelCNN'
  learning_rate: 0.0001
  channels: 16

loss:
  name: 'MILoss'

ploss:
  name: 'CECondLoss'

device: 'cpu'
n_epochs: 50
gamma: 0.0
beta: 0.000
method: 'compression'
nclass_outcome: 1
nclass_sensitive: 18