experiment: "heritage-adv"

data:
  train: '../data/to-ml-heritage/heritage-train.csv'
  validate: '../data/to-ml-heritage/heritage-validate.csv'
  test: '../data/to-ml-heritage/heritage-test.csv'
  name: 'HeritageDataset'

batch_size: 128

net:
  name: 'FCVAE'
  zdim: 24
  depth: 2
  depth_dec: 2
  width_dec: 128
  width: 128
  input_dim: 65
  learning_rate: 0.001
  sdim: 18

pmodel:
  name: 'MLP'
  width: 256
  depth: 2
  learning_rate: 0.0001
  zdim: 24
  nclass: 18

loss:
  name: 'L2Loss'

ploss:
  name: 'MCELoss'

device: 'cpu'
n_epochs: 50
beta: 0.0
method: 'adversarial'
nclass_outcome: 1
nclass_sensitive: 18